### ISSUE TITLE
is there a way to get pressure field in InternalWaveModel?

### ISSUE THREAD

**Issue by qyxiao** [Energy-Pathways-Group/GLOceanKit#51]
Hi, thanks for developing this useful package. I just wonder is there any function to get the pressure field? The example given only mentions getting u, v, w and density from wavemodel. 
The reason I want to get the pressure field is because I want to generate a internal wave field with free surface and make use of the sea surface height data, but it seems your implementation assumes rigid lid. So a way to generate that sea surface height would be get the pressure at z=0 and get the height anomaly by hydrostatic balance. But if you think there's a better way of doing this, please let me know. 

Thank you very much for the help!

**Comment by JeffreyEarly** [comment]
Thanks for the kind words!

Yes, you can get pressure with `wvm.VariableFieldsAtTime(0,'p')`, which ultimately does the [computation here](https://github.com/Energy-Pathways-Group/GLOceanKit/blob/master/Matlab/WaveVortexModel/%40WaveVortexModel/InternalVariableFieldsAtTime.m). Dividing by `self.rho0*self.g` and pulling off the surface value should give you ssh, just as you said.

A hydrostatic free-surface version of the model is fairly high priority and fairly straightforward to add---so hopefully it won't be too much longer!

**Comment by qyxiao** [comment]
Thank you very much for the tips!
