### ISSUE TITLE
One or more output arguments not assigned during call to "varargout" for InternalWaveModel

### ISSUE THREAD

**Issue by qyxiao** [Energy-Pathways-Group/GLOceanKit#53]
Hi, I'm trying to use the newest version of this package but encounter an error saying:
```
One or more output arguments not assigned during call to "varargout".

Error in InternalWaveModelArbitraryStratification/ComputeModesForK2UniqueIndex (line 321)
            [F,G,h,~,F2_,N2G2_,G2_] = self.internalModes.ModesAtWavenumber(sqrt(kk));

Error in InternalWaveModelArbitraryStratification/ComputeModesForNonzeroWavenumbers (line 214)
                self.ComputeModesForK2UniqueIndex(index);

Error in InternalWaveModelArbitraryStratification/InitializeWithSpectralFunction (line 181)
            self.ComputeModesForNonzeroWavenumbers( 1 );

Error in InternalWaveModel/InitializeWithGMSpectrum (line 798)
            [GM3Dint,GM3Dext] = self.InitializeWithSpectralFunction(GM2D_int,varargin{:});

Error in Untitled (line 21)
wavemodel.InitializeWithGMSpectrum(1.0);
```
I have included path to GLNumericalModelingKit and chebfun. I'm following the example for InternalWaveModel with ArbitraryStratification:
```
aspectRatio = 8;

Lx = 100e3;
Ly = aspectRatio*100e3;
Lz = 5000;

Nx = 64;
Ny = aspectRatio*64;
Nz = 100; % 2^n + 1 grid points, to match the Winters model, but 2^n ok too.

latitude = 31;

[rho, ~, zIn] = InternalModes.StratificationProfileWithName('exponential');
z = linspace(min(zIn),max(zIn),100)';
maxModes = 32;
wavemodel = InternalWaveModelArbitraryStratification([Lx, Ly, Lz], [Nx, Ny, Nz], rho, z, latitude, 'nModes', maxModes);

wavemodel.InitializeWithGMSpectrum(1.0);
```

**Comment by JeffreyEarly** [comment]
There are a ton of changes that recently happened, and a bunch more happening really soon.

First, the modern version of the code is now in the folder WaveVortexModel. That code is almost identical to the InternalWaveModel code you have been using, and should be an easy transition. However, note that there are only two functioning versions of the code,

- `WaveVortexModelHydrostatic` uses arbitrary stratification, but is hydrostatic only.
- `WaveVortexModelConstantStratification` is non-hydrostatic, but uses only constant stratification.
- The fully non-hydrostatic, arbitrary stratification code is a few months out still. There were some mathematical complications that we have resolved, but we haven't implemented it in code yet. **So unfortunately, the non-hydrostatic code is currently broken.** Hopefully you can use the hydrostatic version for your problem?

Second, there is a *huge* refactor happening right now which will add a ton of amazing new features. This is on the branch [integrator-tracer-floats-refactor](https://github.com/Energy-Pathways-Group/GLOceanKit/tree/integrator-tracer-floats-refactor). After this refactor I expect the code base will become much more stable. 

Hope that helps!

**Comment by qyxiao** [comment]
Thanks Jeffrey. When I run the following code I still got an error:
```
aspectRatio = 8;

Lx = 100e3;
Ly = aspectRatio*100e3;
Lz = 5000;

Nx = 64;
Ny = aspectRatio*64;
Nz = 65; % 2^n + 1 grid points, to match the Winters model, but 2^n ok too.

latitude = 31;

%%
[rho, ~, zIn] = InternalModes.StratificationProfileWithName('exponential');
z = linspace(min(zIn),max(zIn),65)';
maxModes = 32;
wavemodel = WaveVortexModelHydrostatic([Lx, Ly, Lz], [Nx, Ny, Nz], latitude, rho);
```

```
Unrecognized function or variable 'dLnN2func'.

Error in WaveVortexModelHydrostatic (line 103)
            self.dLnN2Function = dLnN2func;

Error in Untitled (line 18)
wavemodel = WaveVortexModelHydrostatic([Lx, Ly, Lz], [Nx, Ny, Nz], latitude, rho);
```

When I look at the code for WaveVortexModelHydrostatic, it seems like 'dLnN2func' shouldn't be initialized since in my input I haven't specified 'dLnN2func' but still at line 103 the function tries to assign 'dLnN2func' to 'self.dLnN2Function' regardlessly.

**Comment by JeffreyEarly** [comment]
Check out the [Cyprus eddy example](https://github.com/Energy-Pathways-Group/GLOceanKit/tree/master/Matlab/WaveVortexModel/Example/CyprusEddy), which repeats the calculation from the JFM paper.

This restriction will be gone soon, but in the short term, you have to specify the all three function rho(z), N2(z), and d/dz ln(N2), e.g.,

```matlab
rhoFunction = @(z) rho0*(1 + L_gm*N0*N0/(2*g)*(1 - exp(2*z/L_gm)) - (Nmin*Nmin/g)*z);
N2Function = @(z) N0*N0*exp(2*z/L_gm) + Nmin*Nmin*ones(size(z));
dLnN2Function = @(z) 2*ones(size(z))/L_gm;

zIn = [-2000 0];

wvm = WaveVortexModelHydrostatic([Lx, Ly, max(zIn)-min(zIn)], [Nx, Ny, nModes], latitude, rhoFunction,'N2func', N2Function, 'dLnN2func',dLnN2Function);
```

**Comment by qyxiao** [comment]
Thanks, that helps!
